### ISSUE TITLE
Password can still be stolen?

### ISSUE THREAD

**Issue by michalrus** [msharov/pinentry-xlib#1]
Hey!

Your README gave me a lot of hope.

1. I added this to my `/etc/X11/xorg.conf`:
    ```
    Section "Extensions"
      Option	"RECORD"	"Disable"
      Option	"XTEST"		"Disable"
      Option	"XFree86-DGA"	"Disable"
    EndSection
    ```
2. Restarted the X server.
3. Run this in a spare terminal:
    ```
    $ xinput list |
        grep -Po 'id=\K\d+(?=.*slave\s*keyboard)' |
        xargs -P0 -n1 xinput test
    ```
4. Started pinentry.
5. `xinput test` still outputs all the keys that I’m pressing and releasing in pinentry. :crying_cat_face: 

What do you think of that? Did I miss something?

**Comment by michalrus** [comment]
See also https://theinvisiblethings.blogspot.com/2011/04/linux-security-circus-on-gui-isolation.html

**Comment by msharov** [comment]
You are quite right. I did not expect XInput to do this. Apparently it has direct access to any device, even when pinentry does XGrabKeyboard. That should not happen, so this is a bug in XOrg. Whether anybody over there is interested in fixing it is another story, considering the article is from 2011. Sucks to be us...

**Comment by msharov** [comment]
I opened a bug on the XOrg bugtracker.
https://bugs.freedesktop.org/show_bug.cgi?id=103581
We'll see what comes of that, if anything.

**Comment by michalrus** [comment]
Thank you very much! It might just be broken by design. :disappointed: I’m curious as to what they say.

**Comment by michalrus** [comment]
See also https://fedorapeople.org/~dwalsh/SELinux/Presentations/sandbox.pdf

How much work they put into SELinux sandboxes, uhh, this doesn’t look good in the context of this issue we’re having.

**Comment by michalrus** [comment]
Related: https://firejail.wordpress.com/documentation-2/x11-guide/

**Comment by msharov** [comment]
Sandboxing of any kind is not appropriate here and not related. It is supposed to be possible to lock down Xorg's input to a single window. The spec for GrabKeyboard says so. Xorg does not, so it is their bug. If they refuse to fix the bug, as is entirely possible, then we are screwed. That's basically the situation.

**Comment by michalrus** [comment]
Totally! I only meant it as a maybe slightly-related pointer for anyone looking for a—currently possible—way of having more secure pin entry. =)

**Comment by msharov** [comment]
The XInput developers have refused to fix the bug, so there is nothing further to be done. I have removed all mention of securing pinentry against keyloggers from the README file by commit d52917693c30522412820973ae9da2972b2ae871. This issue is therefore closed as "can't fix".

**Comment by michalrus** [comment]
Let me weep quietly in a corner. :sob:

Thank you for all that you did in that thread. :lion:

They have failed us. :broken_heart:
